export const gymFlowAccessTheme = {
  background: "#FFFFFF",
  surface: "#FFFFFF",
  splashBackground: "#0B1328",
  primary: "#1F2A44",
  blue: "#4F7DFF",
  violet: "#6A5CFF",
  accent: "#4F7DFF",
  accentPressed: "#416DE5",
  text: "#1F2A44",
  muted: "#737D91",
  subtle: "#A7AFBD",
  border: "#E6EBF2",
  inputBackground: "#FFFFFF",
  surfaceSoft: "#F4F6FA",
  error: "#B42318",
  errorBackground: "#FEF3F2",
  disabled: "#B8C2D2",
  disabledEnd: "#AEB8CA",
  fonts: {
    regular: "Inter_400Regular",
    medium: "Inter_500Medium",
    semiBold: "Inter_600SemiBold",
    bold: "Inter_700Bold",
    extraBold: "Inter_800ExtraBold",
  },
} as const;
