import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#05070A",
    position: "relative",
  },
  keyboardAvoiding: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 42,
  },
  center: {
    flex: 1,
    backgroundColor: "#05070A",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  loadingText: {
    marginTop: 14,
    fontSize: 16,
    color: "#A7B0BD",
  },
  errorTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#F8FAFC",
    marginBottom: 8,
  },
  errorText: {
    fontSize: 16,
    color: "#DC2626",
    textAlign: "center",
  },
  errorHint: {
    marginTop: 10,
    fontSize: 14,
    color: "#A7B0BD",
    textAlign: "center",
  },
  screenHeader: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  screenBackButton: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: "#111722",
    borderWidth: 1,
    borderColor: "#263241",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  screenHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  screenHeaderTitle: {
    color: "#F8FAFC",
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 35,
  },
  screenHeaderSubtitle: {
    color: "#A7B0BD",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 22,
    marginTop: 4,
  },
  screenProfileButton: {
    width: 50,
    height: 50,
    borderRadius: 999,
    backgroundColor: "#1F2937",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  clientMessagesHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 18,
  },
  clientMessagesHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  clientMessagesSearchBox: {
    minHeight: 54,
    borderRadius: 19,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  clientMessagesSearchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: "800",
    paddingVertical: Platform.OS === "ios" ? 12 : 8,
  },
  clientMessagesSearchClear: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedMessagesAdminActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  unifiedMessagesAdminAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  unifiedMessagesAdminSecondaryAction: {
    borderWidth: 1,
  },
  unifiedMessagesAdminActionText: {
    fontSize: 13,
    fontWeight: "900",
  },
  unifiedMessagesAccessCard: {
    padding: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  unifiedMessagesAccessIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedMessagesAccessCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedMessagesAccessTitle: {
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  unifiedMessagesAccessText: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  unifiedMessagesAccessButton: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedMessagesFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginBottom: 14,
  },
  unifiedMessagesSubHeader: {
    marginBottom: 18,
    gap: 14,
  },
  chatMessagesSubHeader: {
    marginBottom: 10,
    gap: 10,
  },
  unifiedMessagesSubHeaderTop: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  chatMessagesSubHeaderTop: {
    minHeight: 48,
  },
  unifiedMessagesSubHeaderCopy: {
    width: "100%",
    minWidth: 0,
  },
  chatMessagesSubHeaderCopy: {
    paddingBottom: 0,
  },
  unifiedMessagesList: {
    gap: 12,
  },
  chatScreenContainer: {
    flex: 1,
    minHeight: 0,
    marginHorizontal: 0,
    marginTop: 0,
    paddingHorizontal: 18,
    paddingTop: 0,
  },
  chatFixedHeader: {
    flexShrink: 0,
  },
  chatMessagesList: {
    flex: 1,
    minHeight: 0,
  },
  chatMessagesListContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingBottom: 16,
  },
  chatMessagesListContentRegular: {
    paddingTop: 18,
  },
  chatReadScrollContent: {
    paddingTop: 18,
    paddingBottom: 16,
  },
  chatMessageSeparator: {
    height: 12,
  },
  chatComposerFixed: {
    flexShrink: 0,
  },
  unifiedComposerCard: {
    padding: 16,
    gap: 14,
  },
  unifiedComposerNotice: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  unifiedComposerNoticeText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  unifiedComposerSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  unifiedComposerSectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  unifiedRecipientsCount: {
    fontSize: 12,
    fontWeight: "900",
  },
  unifiedOptionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  unifiedOptionButton: {
    width: "48%",
    minHeight: 64,
    borderWidth: 1,
    borderRadius: 18,
    padding: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  unifiedOptionCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedOptionTitle: {
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 18,
  },
  unifiedOptionMeta: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "800",
  },
  unifiedRecipientsBlock: {
    gap: 9,
  },
  unifiedSelectedPersonCard: {
    borderWidth: 1,
    borderRadius: 20,
    minHeight: 66,
    paddingVertical: 10,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  unifiedSelectedPersonSmallAction: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedPersonPickerButton: {
    borderWidth: 1,
    borderRadius: 20,
    minHeight: 68,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  unifiedPersonPickerIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedRecipientCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedRecipientName: {
    fontSize: 13,
    fontWeight: "900",
  },
  unifiedRecipientRole: {
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  unifiedDeliveryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 9,
  },
  unifiedDateTimeBlock: {
    gap: 9,
  },
  unifiedDateTimeButton: {
    minHeight: 70,
    borderRadius: 20,
    borderWidth: 1,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  unifiedDateTimeIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  unifiedDateTimeCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedDateTimeValue: {
    fontSize: 15,
    fontWeight: "900",
    lineHeight: 20,
  },
  unifiedDateTimeHint: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  unifiedComposerPreview: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 13,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  unifiedComposerPreviewCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedComposerPreviewTitle: {
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  unifiedComposerPreviewText: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  unifiedMessagesAutomationAction: {
    minHeight: 48,
    borderRadius: 17,
    paddingHorizontal: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  unifiedAutomationCard: {
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  unifiedAutomationSystemCard: {
    marginBottom: 12,
  },
  unifiedAutomationCopy: {
    flex: 1,
    minWidth: 0,
  },
  unifiedAutomationTitle: {
    fontSize: 15,
    fontWeight: "900",
    lineHeight: 20,
  },
  unifiedAutomationText: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  unifiedAutomationMeta: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: "900",
  },
  unifiedAutomationActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  unifiedAutomationSmallButton: {
    minHeight: 34,
    borderRadius: 13,
    borderWidth: 1,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  unifiedAutomationSmallText: {
    fontSize: 11,
    fontWeight: "900",
  },
  clientMessagesLoadingCard: {
    minHeight: 108,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  clientMessagesLoadingText: {
    fontSize: 13,
    fontWeight: "800",
  },
  clientHomeEyebrow: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  clientHomeTitle: {
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 35,
  },
  clientHomeSubtitle: {
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 4,
  },
  trainerRoutineFeedback: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  trainerRoutineFeedbackText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 17,
  },
  clientAccountBackButton: {
    width: 48,
    height: 48,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  headerProfileImage: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  primaryButton: {
    marginTop: 16,
    backgroundColor: "#E33B3B",
    borderWidth: 1,
    borderColor: "#E33B3B",
    borderRadius: 8,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 15,
  },
  bottomDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
    backgroundColor: "#0B1017",
    borderTopWidth: 1,
    borderTopColor: "#263241",
    shadowColor: "#000000",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -8 },
    elevation: 12,
  },

  bottomDockInFlow: {
    position: "relative",
    flexShrink: 0,
  },

  bottomDockButton: {
    flex: 1,
    minHeight: 60,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderTopWidth: 3,
    borderTopColor: "transparent",
  },

  bottomDockButtonActive: {
    backgroundColor: "transparent",
  },

  bottomDockButtonDisabled: {
    opacity: 0.45,
  },

  bottomDockIconWrap: {
    position: "relative",
    minWidth: 30,
    alignItems: "center",
  },

  notificationBadge: {
    position: "absolute",
    top: -9,
    right: -12,
    minWidth: 20,
    height: 20,
    borderRadius: 999,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#0B1017",
  },

  notificationBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    lineHeight: 12,
  },

  bottomDockText: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },

});
